### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by TowelSniffer** [lovac42/JSLoader#4]
I don't mean to harras you, but the latest update apparently fixed the night mode bug, however it still fails on me if I enable night mode.

**Comment by lovac42** [comment]
NM uses a unique method of patching into Anki that causes problem for ALL addons. Just make sure it loads last after all other addons have been loaded by changing it's folder name with a z prefix. ```z828472```. Or change this addon's folder name with an 'a' prefix ```a93928```. But changing folder names will prevent updates notifications, so it is far better to change nightmode as it screws up all other addons.

**Comment by TowelSniffer** [comment]
that solves it :)
